@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 5
skinparam maxmessagesize 180
skinparam sequenceParticipant bold
title Create Entitlement
actor "Integrating application user" as User #CornflowerBlue
participant "Integrating application" as A #CornflowerBlue
participant "<FHIR API> NES Entitlement" as B #CornflowerBlue
participant "DB" as C #CornflowerBlue
|||
User -> A: Provide details for the entitlement to be created
activate A
|||
A -> B: POST[base]/Coverage
activate B
|||
B -> B: Validate[]
|||
B -> C: Create
activate C
|||
C -[dashed]-> B:  
deactivate C
|||
B -[dashed]-> A: HTTP 201 - Return newly created Entitlement
deactivate B
|||
A -> User: Display entitlement details
deactivate A
|||
@enduml
