@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 5
skinparam maxmessagesize 180
skinparam sequenceParticipant bold
title  Enrolment Nomination Request
participant "FHIR Client" as A #CornflowerBlue
participant "NES " as B #CornflowerBlue
participant "EEE" as C #CornflowerBlue

A -> B: POST[base]/EpisodeOfCare
B -> B: Validate
B -> C: create
C -[dashed]-> B:

B -[dashed]-> A:Newly created NESEnrolment
@enduml