@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 5
skinparam maxmessagesize 180
skinparam sequenceParticipant bold
title  Enrolment Nomination Request
participant "Whaihua" as AA #CornflowerBlue
participant "NES " as A #CornflowerBlue
participant "Healthlink Air Broker" as B #CornflowerBlue
participant "PMS" as C #CornflowerBlue
|||

AA -> A: 1. POST [base]/$process-message
activate A
A -> A:  2. validate and enrich

A -> B: 3. POST [base]/$process-message
activate B
|||
B -> B: 4. Transform to HL7 v2[]
|||
B -> C: 5. ADT^28 request
B -[dashed]-> A: 6. 202 Response 
deactivate B
A -[dashed]-> AA: 7. 202 Response 

deactivate A
|||
@enduml