@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 5
skinparam maxmessagesize 180
skinparam sequenceParticipant bold
title  Enrolment Nomination Request
participant "Whaihua" as AA #CornflowerBlue
participant "NES " as A #CornflowerBlue
participant "Healthlink Air Broker" as B #CornflowerBlue
participant "PMS" as C #CornflowerBlue
|||

AA -> A: POST [base]/$process-message
activate A
A -> A:  validate and enrich

A -> B: POST [base]/$process-message
activate B
|||
B -> B: Transform to HL7 v2[]
|||
B -> C: ADT^28 request
B -[dashed]-> A: 202 Response 
deactivate B
A -[dashed]-> AA: 202 Response 

deactivate A
|||
@enduml