@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 5
skinparam maxmessagesize 180
skinparam sequenceParticipant bold
title  Enrolment Nomination Response
participant "NES " as A #CornflowerBlue
participant "Healthlink Air Broker" as B #CornflowerBlue
participant "PMS" as C #CornflowerBlue
|||

C-> B: 1. ADT^28 ACK response
activate B
|||
B -> B: 2. Transform HL7 v2 to FHIR
|||
B -> A:  3. POST [base]/$process-message
activate A
|||
A -[dashed]-> B: 4. 202 Response 
|||
deactivate A
deactivate B
|||
@enduml
