@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 5
skinparam maxmessagesize 180
skinparam sequenceParticipant bold
title  Enrolment Nomination Request
participant "NES " as A #CornflowerBlue
participant "<FHIR API> Messaging Hub" as B #CornflowerBlue
participant "PMS" as C #CornflowerBlue
|||

C-> B: ADT^28 ACK response
activate B
|||
B -> B: Transform HL7 v2 to FHIR
|||
B -> A:  POST [base]/$process-message
activate A
|||
A -[dashed]-> B: 200 Response 
|||
deactivate A
|||
@enduml
