@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 5
skinparam maxmessagesize 180
skinparam sequenceParticipant bold
title  Enrolment Nomination Request
participant "NES " as A #CornflowerBlue
participant "<FHIR API> Messaging Hub" as B #CornflowerBlue
participant "PMS" as C #CornflowerBlue
|||

A -> B: POST [base]/$process-message
activate B
|||
B -> B: Transform to HL7 v2[]
|||
B -[dashed]-> A: 200 Response 
B -> C: ADT^28 request
activate C
|||
deactivate C
|||
@enduml

