@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 5
skinparam maxmessagesize 180
skinparam sequenceParticipant bold
title Search Entitlements
actor "Integrating application user" as User #CornflowerBlue
participant "Integrating application" as A #CornflowerBlue
participant "<FHIR API> NES Entitlement" as B #CornflowerBlue
participant "DB" as C #CornflowerBlue
|||
User -> A: Look up persons entitlements using their NHI number
activate A
|||
A -> B: GET [base]/Coverage?beneficiary=[NHI number]
activate B
|||
B -> B: Validate[]
|||
B -> C: Request
activate C
|||
C -[dashed]-> B:  
deactivate C
|||
B -[dashed]-> A :Return Bundle containing persons Entitlement records
deactivate B
|||
A -> User: Display Entitlement details
deactivate A
|||
@enduml
