# ╭────────────────────────────ImplementationGuide-hl7.org.nz.hpi.json─────────────────────────────╮

# │  The properties below are used to create the ImplementationGuide resource. For a list of       │

# │  supported properties, see:                                                                    │

# │  http://build.fhir.org/ig/HL7/fhir-shorthand/branches/beta/sushi.html#ig-development           │

# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯

id: hl7.org.nz.fhir.ig.nes
canonical: http://hl7.org.nz/fhir/ig/nes
version: 1.0.0-SNAPSHOT
name: NewZealandNESIG
title: New Zealand NES IG
status: active
publisher:
  name: Te Whatu Ora
  email: mailto:integration@health.govt.nz
description: The FHIR  API for the NES
license: CC0-1.0
dependencies:
  fhir.org.nz.ig.base:
    uri: 'https://fhir.org.nz/ig/base/'   
    version: dev
  hl7.org.nz.fhir.ig.hip-core:
    uri: https://common-ig-v1-1-0.hip.digital.health.nz/site
    version: 1.2.0
  hl7.org.nz.fhir.ig.nhi:
   uri: 'https://nhi-ig.hip.digital.health.nz/site'   
   version: 1.3.0
fhirVersion: 4.0.1
parameters:
  show-inherited-invariants: false
copyrightYear: 2020+
releaseLabel: Release
# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮

# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │

# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  IG Home: index.html
  Business View: businessView.html
  Use cases:
    Guidance: guidance.html
  Important information:
    Onboarding and Compliance testing: OnboardingAndComplianceTesting.html
    General Notes: general.html
    FAQ: FAQ.html
    Glossary: glossary.html
  API: capabilityStatement.html
  Profiles: profiles.html
  Extensions: extensions.html
  Identifiers: namingSystems.html
  Terminology: terminology.html
  Table of Contents: toc.html
  Artifact Index: artifacts.html
  Support:
    FHIR Spec: new-tab http://hl7.org/fhir/R4/index.html
    Download IG: full-ig.zip
    Artifacts (Json): definitions.json.zip
    Artifacts (Xml): definitions.xml.zip
    
