# ╭────────────────────────────ImplementationGuide-hl7.org.nz.hpi.json─────────────────────────────╮

# │  The properties below are used to create the ImplementationGuide resource. For a list of       │

# │  supported properties, see:                                                                    │

# │  http://build.fhir.org/ig/HL7/fhir-shorthand/branches/beta/sushi.html#ig-development           │

# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯

id: hl7.org.nz.fhir.ig.nes
canonical: http://hl7.org.nz/fhir/ig/nes
version: 1.1.0-SNAPSHOT
name: NewZealandNESIG
title: New Zealand NES IG
status: active
publisher:
  name: Te Whatu Ora
  email: mailto:integration@health.govt.nz
description: The FHIR  API for the NES
license: CC0-1.0
dependencies:
  fhir.org.nz.ig.base:
    uri: 'https://fhir.org.nz/ig/base/'   
    version: 2.0.0
  hl7.org.nz.fhir.ig.hip-core:
    #uri: https://tst.d1gti5r1pqczdn.amplifyapp.com/site
    #version: 1.2.0
    uri: https://common-ig.hip.digital.health.nz/site
    version: 1.3.2
    
  hl7.org.nz.fhir.ig.nhi:
   uri: 'https://nhi-ig.hip.digital.health.nz/site'   
   version: 1.4.2
   
  hl7.org.nz.fhir.ig.hpi:
   uri: 'https://hpi-ig.hip-uat.digital.health.nz'   
   version: 1.2.0
   
fhirVersion: 4.0.1
parameters:
  show-inherited-invariants: false
copyrightYear: 2020+
releaseLabel: Release
# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮

# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │

# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  IG Home: index.html
  Business View: businessView.html
  Use cases:
    Enrolment Nomination: enrolmentNomination.html
    Get Enrolments: getEnrolment.html
    Create Enrolments: createEnrolment.html
  Important information:
    Onboarding and Compliance testing: OnboardingAndComplianceTesting.html
    General Notes: general.html
    FAQ: FAQ.html
    Glossary: glossary.html
  API: API.html
  Profiles: profiles.html
  Message Definitions:
    Enrolment Nomination Request: MessageDefinition-EnrolmentNominationRequestMessageDefinition.html
    Enrolment Nomination Response: MessageDefinition-EnrolmentNominationResponseMessageDefinition.html
  #Extensions: extensions.html
  #Identifiers: namingSystems.html
  Terminology: terminology.html
  Table of Contents: toc.html
  Artifact Index: artifacts.html
  Support:
    FHIR Spec: new-tab http://hl7.org/fhir/R4/index.html
    Download IG: full-ig.zip
    Artifacts (Json): definitions.json.zip
    Artifacts (Xml): definitions.xml.zip
    

    